Switch to new trySlackSend function
Switch all slackSend calls to trySlackSend.   Fixes errors like these
when the Slack Notification Plugin is not configured:

      java.lang.NoSuchMethodError: No such DSL method 'slackSend' found

Signed-off-by: Geoff Levand <geoff@infradead.org>